language: php

php:
  - 7.0

before_script:
 - mv .travis.env .env
 - mysql -e 'create database gottashit_travis;'
 - composer self-update
 - composer install --dev --prefer-source --no-interaction
 - chmod -R 777 storage
 - php artisan key:generate
 - php artisan migrate:install --env=testing --no-interaction -vvv

script:
 - php artisan migrate --env=testing --no-interaction -vvv
 - vendor/bin/phpunit
 - php artisan migrate:rollback --env=testing --no-interaction -vvv

matrix:
 fast_finish: true