version: '3'
services:
  phpgottashit:
    image: gottashit-php
    build:
      context: ""
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/web
      - ~/.ssh:/root/.ssh
      - ~/.config/composer/auth.json:/.composer/auth.json

  webgottashit:
    image: nginx:latest
    volumes:
      - ./:/var/www/web
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker-storage/logs/nginx:/var/log/nginx
    ports:
      - 8000:80
    depends_on:
      - phpgottashit

  mysqlgottashit:
    build: docker/mysql
    environment:
      MYSQL_DATABASE: 'homestead_gottashit'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - 13306:3306
    volumes:
      - ./docker-storage/mysql:/var/lib/mysql